name: CutCopyPaste
options:
  bundleIdPrefix: com.cutcopypaste
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  swift-argument-parser:
    url: https://github.com/apple/swift-argument-parser.git
    from: "1.3.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  CutCopyPaste:
    type: application
    platform: macOS
    sources:
      - path: CutCopyPaste
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cutcopypaste.app
        PRODUCT_NAME: CutCopyPaste
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: CutCopyPaste
        CODE_SIGN_ENTITLEMENTS: CutCopyPaste/Resources/CutCopyPaste.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: true
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: CutCopyPaste/Resources/CutCopyPaste.entitlements

  CutCopyPasteCLI:
    type: tool
    platform: macOS
    sources:
      - path: CutCopyPasteCLI
      - path: CutCopyPaste/Models
      - path: CutCopyPaste/Utilities/Constants.swift
    dependencies:
      - package: swift-argument-parser
        product: ArgumentParser
    settings:
      base:
        PRODUCT_NAME: ccp
        SWIFT_STRICT_CONCURRENCY: complete
        GENERATE_INFOPLIST_FILE: true

  CutCopyPasteTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CutCopyPasteTests
    dependencies:
      - target: CutCopyPaste
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cutcopypaste.app.tests
        GENERATE_INFOPLIST_FILE: true
